#!/bin/sh

# Setup some environment variables needed in mininet runs.

# Root location of the example loadshed app
export APP=`pwd`
[ -z "$RIAPSHOME" ] && export RIAPSHOME=/usr/local/riaps   
[ -z "$RIAPSAPPS" ] && export RIAPSAPPS=/home/riaps/riaps_apps

# Location of the GridlabD agent code

# Edit the next line to point to the location of the GridlabD agent
export GLA=~/workspace/interface.gridlabd.git 


